### ISSUE TITLE
Scientific Protocols - Libre Projects - Knowledge section listing request

### ISSUE THREAD

**Issue by dior001** [libreprojects/libreprojects#109]
### [ScientificProtocols.org](https://www.scientificprotocols.org) - GitHub for Scientific Protocols

The purpose of this site is to provide a free and easy way for scientists to publish and collaborate on scientific protocols. By sharing scientific protocols we hope to encourage transparency in
research and promote reproducibility of published results. [ScientificProtocols.org](https://www.scientificprotocols.org)
is part of the [Reproducibility Initiative](http://validation.scienceexchange.com/#/reproducibility-initiative).

The site is heavily focused on GitHub integration. GitHub provides a rock solid foundation for scientific collaboration. Every protocol created on the [ScientificProtocols.org](https://www.scientificprotocols.org) website is also a [GitHub Gist](https://help.github.com/articles/about-gists).

The core website codebase has been made open source ([MIT License](http://opensource.org/licenses/MIT)) as part of the [Mozilla Science Lab Global Sprint](http://mozillascience.org/).

Repo
https://github.com/sprotocols/scientificprotocols

Wiki
https://github.com/sprotocols/scientificprotocols/wiki

**Comment by yuwash** [comment]
That’s interesting. It’s a good platform technically capable for any scientific area, but just because it’s provided by a mainly biological research organization (the Reproducibility Initiative), the contents are currently limited to that area. What do other @libreprojects/contributors think?

**Comment by dior001** [comment]
Happy 2015 @yuwash. It would be great to see ScientificProtocols.org listed on Libre Projects this year.

**Comment by yuwash** [comment]
Thanks for the interest in our site. Unfortunately there seems to be not much enthusiasm about this topic among other contributors. Though the project seems technically mature, it seems the contents are currently quite biased to the topic of biotechnology. A reason could be the hurdle of requiring submission by git which is quite geeky. It’s an awesome techonlogy so we’re using it here and since we do programming anyway, git isn’t the big issue for us. For projects to showcase in our site, however, we expect them to be easily usable by non-geeky audience.

**Comment by jancborchardt** [comment]
Yup, totally agree with what @yuwash said. Great effort – with Libre Projects we have a specific focus on easily usable projects for mass audiences though. :)
