### ISSUE TITLE
Project suggestion: NAB

### ISSUE THREAD

**Issue by goosyboosy** [libreprojects/libreprojects#133]
Free (libre) Git hosting [notabug.org](https://notabug.org)

**Comment by jancborchardt** [comment]
To quote the [readme](https://github.com/libreprojects/libreprojects#libre-projects):

> It’s not about giving many choices, it’s about providing the best solutions.

We already have [GitLab](https://about.gitlab.com/), which arguably is the best open source solution currently.

Gogs seems to be mostly an experiment in coding something with Go. Since not many hosters support Go, I don’t see the »painless self-hosted« part of the tagline.
