### ISSUE TITLE
Pexels

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#141]
Just as a note to ourselves: https://www.pexels.com/ is a pretty good web service for stock photos which are all CC0 licensed.

@libreprojects/contributors do you know any better alternative to that? Or should we add Pexels?

**Comment by yuwash** [comment]
The site is definitely a great resource to find free stock photos, but since the site itself is not opensource, I’m not sure whether it otherwise really helps the free/opensource culture by restricting to just the CC0 license whereas the most typical (recommended) licenses are CC-BY and CC-BY-SA. Those licenses can be chosen by the uploader on Flickr or Wikimedia Commons and users should be IMO properly instructed to attribute the source no matter if the license requires it or not.

**Comment by ironbishop** [comment]
We already list Wikimedia Commons, that's not limited to stock, but actually promote quality content. I wouldn't list pexels.

**Comment by jancborchardt** [comment]
Good points. Closing then! :)
