### ISSUE TITLE
Gitlab

### ISSUE THREAD

**Issue by tommorris** [libreprojects/libreprojects#18]
[Gitlab](http://gitlabhq.com/) is a self-hosted alternative to Github. Might be good to add to the development section of libreprojects.

**Comment by jancborchardt** [comment]
Hey Tom! I’m aware of Gitlab, but as far as I know there’s no hosted instance. Next to a project being open source & usable, this is one of the most important requirements to be listed on Libre Projects. Otherwise non-technical people have a hard time using the software.

Added it to #10 (projects not fit for adding (yet)) and will close this. Or let me know if there is in fact a service where people can use readily hosted Gitlab-instances.

Thanks!
