### ISSUE TITLE
add contribution opportunities to project details

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#2]
Linked icons to code, issue tracker, translation help, documentation, donation.

**Comment by jancborchardt** [comment]
I was thinking how much we actually want to do on the Libre Projects side, what makes sense and what would be crazy to think we can keep it updated. The code link makes sense as that’s one big part of what we do. But I’m not so sure about issue tracker, translation, docs and donation opportunities. Similarly, I don’t think »personal dev info« (see #1) is something we should do.

Thoughts? @jhuet @ironbishop @Airon90 @yuwash @lucab @sindikat?

**Comment by jancborchardt** [comment]
And same for #5 (aggregated news feeds of project news).

**Comment by airon90** [comment]
Too many info in the details.
I think that, if someone wants to help to a project, he/she can look for info in the website of the project.
IMHO :)

**Comment by jancborchardt** [comment]
Yeah, so in the beginning we had no popup at all, and the icon was a direct link to the project page. But I also think it’s important to provide details to encourage people to contribute.

**Comment by ironbishop** [comment]
I thought LibreProjects was dedicated more to the acknowledgment of free software rather than to its development. In fact, we already have a link to the source code, usually on GitHub which include issue trackers and documentation. So I would not add intricacy to the details popup.

We could add some text to the bottom of the page, explaining that the open community welcomes participation.

**Comment by jancborchardt** [comment]
Oh right – I didn’t really reread the original post. So yes, we kinda solved this issue: We link the actual app, and the code, and the license – that’s enough.
