### ISSUE TITLE
license & code

### ISSUE THREAD

**Issue by jancborchardt** [libreprojects/libreprojects#22]
Currently we don’t have links to the source code. I’m cleaning the games category up right now and will add the »source« attribute to data.json.

Also, the »licenses« attribute should only have one »license« – when it’s multi-licenses, we should just show the most permissive license.

**Comment by jhuet** [comment]
@jancborchardt, not sure about allowing only 1 license as we already have something working with many. Why bother removing that possibility ?

**Comment by jancborchardt** [comment]
Currently, none of the projects uses the 2-license thing. The only thing where I can think of it as useful (or where I wanted to use it) is games, where the code is MIT/AGPL and the graphics are under a CC license. Even in that case I think we should focus on the code license and not complicate the license stuff more. People can still know more on the website of the service.

**Comment by jhuet** [comment]
We're starting to scratch an interesting point here because things might seem confusing in the future if we aren't more specific.

About multi-licenses, i think it could also happen for apps that want a core to be something like AGPL but be more permissive for plugins (i guess it is for ownCloud ?). I agree it's not necessarily of 1st interest though.

On a related topic, when we look for the TOS ratings it's not about the code, it's about the service provided. For example, we have wordpress or diaspora who can have a lot of hosting services using the code of the apps. The license info are about the code, but the TOS ratings are about only 1 of the service providers and we don't say so anywhere.

**Comment by jancborchardt** [comment]
In the case of ownCloud, the license of the plugins is irrelevant I’d say. Especially because you could also install proprietary plugins, but mostly they will be either AGPL or more permissive. It will get really unmanageable, and that info is not for us to keep track of. Basic license info yes (to make clear it’s free software), but detailed should be on the site of the project itself (by the way, the license image should probably link to the license page of the project).

And yes, the TOS-ratings will be more complicated. But since we almost always link to one specific instance rather than the project page, we have to take the rating from that. And linking to a specific usable isntance is the point, being easily accessible – most people don’t know the distinction of »project site« and »hosted instance«.

**Comment by airon90** [comment]
This bug is going to be fixed with future commits so I'm closing this bug :)
