### ISSUE TITLE
Current version of Teambox software is not open source

### ISSUE THREAD

**Issue by arthurlutz** [libreprojects/libreprojects#29]
Teambox 4 is not open source : http://teambox.com/open-source/

Until it is, I suggest it be removed from libreprojects

Thanks for a great inventory.

**Comment by airon90** [comment]
What about this?
https://github.com/teambox/teambox

**Comment by arthurlutz** [comment]
"This repository is for Teambox v3. Teambox.com is running v4, which is a cloud-only service, not available for download." 

To keep Teambox in the listing, maybe it should be explicit v3 and point to github and not teambox.com... but is it still maintained ? Last commit 5 months ago, 15 open pull requests ?

**Comment by jancborchardt** [comment]
Good catch @arthurlutz, I was puzzled about Teambox for some time because I think they changed it around a few times.

I’d say we throw it out, because they went proprietary with the current version. The old v3 isn’t hosted anywhere and the code is stale anyway. There’s 2 or 3 more project management softwares in the list anyway so it’s ok.

What do you think @Airon90 @jhuet?

**Comment by jhuet** [comment]
:+1:

**Comment by airon90** [comment]
:+1: for me too

**Comment by jancborchardt** [comment]
Ok, removed it, sorry for the delay. Keep in mind you can always issue pull requests yourself. :)
Thanks again to @arthurlutz for noting it!
