### ISSUE TITLE
trashwiki

### ISSUE THREAD

**Issue by guaka** [libreprojects/libreprojects#61]
Please add http://trashwiki.org/, the collaborative world wide guide of creating value from trash

**Comment by yuwash** [comment]
Although I acknowledge that
- the wiki is based on the floss MediaWiki,
- it has informative contents, 
- its contents are licensed as cc-by-nc-sa and
- the idea discussed in the wiki is related to freedom,

since it's not a software project (i. e. developing MediaWiki) but a knowledge project, I'd wish the contents could be downloaded as well. (as can be all the Wikimedia projects)
libreprojects shouldn't become a [Wiki Index](http://wikiindex.org)

**Comment by guaka** [comment]
ok :)

**Comment by jancborchardt** [comment]
Yeah – while I use and like Trashwiki (thank you @guaka!), I tend to agree with @yuwash here.

What would probably make me add Trashwiki:
- if the content was licensed cc-by-sa (without restrictive noncommercial clause)
- if you issue a pull request directly, adding it to the [data.json](https://github.com/libreprojects/libreprojects/blob/gh-pages/js/data.json) and including a logo
