### ISSUE TITLE
ASCII Flow - flow charts in ascii

### ISSUE THREAD

**Issue by lightonflux** [libreprojects/libreprojects#68]
ASCIIFLOW is a tool to create ascii flow charts

http://www.asciiflow.com/

[Here the license file](https://github.com/lewish/asciiflow/blob/dev/LICENSE) (BSD 3-clause).

Something else you need to know?

**Comment by jancborchardt** [comment]
Hm, it seems more like a tool for geeks than a generally useful showcase of open source software for »normal« people. ;) If it would be a great flowchart program with a nice interface which can export flowcharts in some open format or as SVG, then we would add it of course.

@libreprojects/contributors what do you think?

**Comment by lucab** [comment]
I disagree.
Even in working environments, sometimes you are forced to embed diagram in text-area (eg. code comments, RFC draft, etc.) and having a tool to do that is _really_ time-saving.

:thumbsup: from me

**Comment by ironbishop** [comment]
It's a niche software. It's clever. But LP already contains softwares that probably I will never use. I think it's :+1: for me also. We could order the projects for usefulness, inside the categories.But that would be subjective.

**Comment by jancborchardt** [comment]
@ironbishop that’s a very specific environment. ;) It’s a flowchart tool which is probably not useful for most people who need to create flowcharts, because usually flowcharts are not in ascii.

@ironbishop what is some software on Libre Projects which is too geeky or not well usable?

I know there are many more open source web apps out there than we list on the site. But our focus is on showcasing the best ones, those which are really well designed, and useful for many people except being a cool niche project.

For example, there are many other open source social networks except Diaspora and Friendica, but our purpose is not to list them all because that’s not really useful to help people show what’s the best stuff. It’s more like a »featured apps« site.

**Comment by ironbishop** [comment]
Wait: if **I** don't use something, it doesn't mean it's not useful for someone else. In this specific case, it's clear that only few people would use this. Maybe we could create a new category, like "geek", for projects like this?

Would pijs enter this category?

**Comment by jancborchardt** [comment]
@ironbishop I was asking if you feel like there’s software on Libre Projects which does not fit our goal »open source, web based and usable«. I know the curation process can be quite subjective in the end, but that’s how it is. And sometimes I just have to say no to certain things. :)

For example, I don’t want to have a »geek« kitchen-sink category on there where we can add all the geeky projects. (Apart from that, Pijs is not really fit for adding for the reasons mentioned in #63) Libre Projects specifically aims to showcase to non-geeks that there are awesome web projects which happen to be open source.

There are enough directories already listing each and every web based open source project not curating that much really, and most of them are listed at https://github.com/libreprojects/libreprojects/issues/7

We also have a site where we list all projects which are too geeky to add or otherwise not fit for adding, and it’s at https://github.com/libreprojects/libreprojects/issues/10

Hope that clears it up. :)

**Comment by ironbishop** [comment]
Clear. We can close the issue, since Asciiflow is not in scope.
